# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/imports/Integration/space_invader_draft.srcs/sources_1/new/Oled_Display.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/Start.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/bullet_CD_display.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/bullet_module.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/clk_625m.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/difficulty_choose.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/imports/Integration/FDPvivado1.srcs/FDPvivado1.srcs/sources_1/new/enemy_master.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/imports/Integration/FDPvivado1.srcs/FDPvivado1.srcs/sources_1/new/enemy_move.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/enemy_package.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/imports/Integration/FDPvivado1.srcs/FDPvivado1.srcs/sources_1/new/enemy_unit.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/hp_bar.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/move_pulse.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/on_press.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/over.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/play.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/imports/Integration/FDPvivado1.srcs/FDPvivado1.srcs/sources_1/new/position_check.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/priority_module.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/pulse.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/reset_enemy_new.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/score_display.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/imports/Integration/space_invader_draft.srcs/sources_1/new/starship.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/imports/Integration/space_invader_draft.srcs/sources_1/new/starship_design.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/state_crl.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/imports/Integration/space_invader_draft.srcs/sources_1/new/xy_coordinate.v
  C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/sources_1/new/Top_student.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/constrs_1/new/my_constriant.xdc
set_property used_in_implementation false [get_files C:/Users/XuZihao/Documents/GitHub/EE2026-Star-War/project_123.xpr/project_1/project_1.srcs/constrs_1/new/my_constriant.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_student_utilization_synth.rpt -pb Top_student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
